### ISSUE TITLE
Conversion tracking does not work with 1.11.8

### ISSUE THREAD

**Issue by SirRahikkala** [krokedil/klarna-checkout-for-woocommerce#306] opened 2020-04-20 13:40 UTC
After the changes between 1.11.7 and 1.11.8 the conversion tracking has stopped working with Facebook Pixel events as well the Google analytics e-commerce conversions therefore the order complete status (or similar) is never passed to any of the services. For example the UTM source tags are missing etc.

**Comment by NiklasHogefjord** [comment] 2020-04-22 11:33
Hi @SirRahikkala,
I don't think that we have done any direct changes in the plugin between 1.11.7 and 1.11.8 that should affect Google analytics. You can see the changes in the commit history here: https://github.com/krokedil/klarna-checkout-for-woocommerce/commits/1.11.8.

Regarding 1.11.8 it will be available for those who still are experiencing issues with 2.x and want to revert. But to be absolutely clear - from what we can see the current issue (with some customers not being able to finalize the purchase) points to an issue in Klarnas system (or with some of the banks that Klarna communicates with during a transaction). It does not look like it is an issue in this plugin.

**Comment by SirRahikkala** [comment] 2020-04-22 11:36
Are you referring with that unable to finish purchase to v.2.x? Because we had to update from 1.11.8 to 2.0.12 and immediately we started having orders not finalized. The Klarna merchant portal does not have an order but logs show 15-16 entries of status 200. No errors on any logs anywhere. We tried to follow whats going on with Hotjar screen recordings but since the iframe visibility is blocked we can only guess what goes on behind it.

**Comment by MichaelBengtsson** [comment] 2020-05-07 06:17
Hi @SirRahikkala

Yes that issue seemed like it came from Klarna even if they dont show any errors. It seemed like it had to do with the 3DS part of their checkout. At the point where the order is created in WooCommerce, we hand everything over to Klarna to finalize the order on their part. This means 3DS and their own validation and credit checks for the customer. It looked lite it was in those steps that the order usually failed in some way that was not logged by Klarna. They have however released updates to their system that fixed some of the issues we could reproduce, and last week they released a fix for the 3DS part of the process.

**Comment by MichaelBengtsson** [comment] 2020-06-08 06:38
I will be closing this issue since its relating to a branch that we are no longer developing on. If this is an issue even in the newer versions of the plugin please let us know and reopen the issue/create a new one.

**Closed by MichaelBengtsson** 2020-06-08 06:38 UTC
