### ISSUE TITLE
Mix of checkout and thank you when free order.

### ISSUE THREAD

**Issue by jonasostrom** [krokedil/klarna-checkout-for-woocommerce#94] opened 2018-09-18 18:53 UTC
Hi,

I've updated to the 1.6.0 version and discovered that the commit:
`Don’t use KCO template file if cart doesn’t need payment.`
Now gives me the default checkout when it is free order but I have experienced that the klarna widget comes as "Thank you" and says that my cart is empty?

**Comment by MichaelBengtsson** [comment] 2018-10-08 08:12
@jonasostrom I am not able to reproduce this. Do you have steps to follow to get this to trigger?

**Comment by MichaelBengtsson** [comment] 2019-03-15 08:35
Closing this as i can't recreate this anymore using the steps above. If this is still an issue for you, feel free to reopen this issue and i will investigate it again.

**Closed by MichaelBengtsson** 2019-03-15 08:35 UTC
