### ISSUE TITLE
Missing 'checked' value in 'merchant_requested.additional_checkboxes' response from Klarna Checkout API

### ISSUE THREAD

**Issue by supermagnus** [krokedil/klarna-checkout-for-woocommerce#531] opened 2023-05-02 18:07 UTC
### Description of the issue
The Klarna Checkout API response is missing a boolean value (`true` or `false`) for the `checked` field within the `merchant_requested.additional_checkboxes` array. The field appears empty, which affects our implementation that relies on the `checked` value to determine if a customer has given marketing consent.

### Expected behavior
The `checked` field in the `merchant_requested.additional_checkboxes` array should have a boolean value (`true` or `false`).

`"merchant_requested": {
  "additional_checkboxes": [
    {
      "id": "terms_and_conditions",
      "checked": true
    },
    {
      "id": "marketing_consent",
      "checked": false
    }
  ]
}`

### Actual behavior
The `checked` field in the `merchant_requested.additional_checkboxes` array appears empty, without a boolean value.

`"merchant_requested": {
  "additional_checkboxes": [
    {
      "id": "terms_and_conditions",
      "checked": ""
    },
    {
      "id": "marketing_consent",
      "checked": ""
    }
  ]
}`

### Steps to reproduce the behavior
1. Set up Klarna Checkout for WooCommerce with additional checkboxes for marketing consent.
2. Complete a test checkout and give or deny marketing consent.
3. Check the API response for the `merchant_requested.additional_checkboxes` array.
4. Observe that the checked field is missing a boolean value.

### Klarna plugin version
Klarna Checkout for WooCommerce v2.10.1

### WordPress version
WordPress v6.2

### WooCommerce version
WooCommerce v7.6.1

### Screenshots
<img width="465" alt="image" src="https://user-images.githubusercontent.com/12447613/235748785-2cafd019-845e-4163-8bae-4c70edcd9597.png">

**Comment by Pautomagi** [comment] 2023-05-07 21:01
Having a similar issue but we can see the `[checked]` being false.
We have made it be `true` one time by clicking it once after the pop up window callback closes.
It seems to then reset the klarna iframe (the box is now unticked). But if you are fast enough to check the box again before the page redirects you to the thank you it will be true.
Let me know if I can provide any more information or data to help debug.

**Comment by mntzrr** [comment] 2023-08-22 06:15
@supermagnus it looks like you output the content using `print_r` which renders `false` as empty string. I suggest you use `var_dump` instead.

```php
<?php
$json = '{"additional_checkboxes":[{"id":"terms_and_conditions","checked":false},{"id":"custom_checkbox","checked":false}]}';
print_r(json_decode($json));
var_dump(json_decode($json));
``` 

 @Pautomagi, I am also getting `false` although the checkbox is obviously checked.

I also tried postponing triggering the action hook until we reach the confirmation page, but I still get the same result. I've reached out to our Klarna partner to find out more.

**Comment by mntzrr** [comment] 2024-01-09 12:23
The issue related to checked still being reported as `false` should now have been resolved by Klarna. I've confirmed that it works on my end as well. And like I mentioned, the empty content of `unchecked` is related to how `print_r` handle `false`. I am therefore closing this issue, but if you're still having issues, feel free to reopen it.

**Closed by mntzrr** 2024-01-09 12:23 UTC
