### ISSUE TITLE
Support Klarna's Cross-sell functionality (aka Upsell, Remarketing)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#137] opened 2018-12-06 12:05 UTC
Cross-selling is a feature for KCO that offers customers the possibility to add additional items, after they have already completed their purchase and been redirected to the confirmation page.
The feature allows the merchant the ability to update an already existing order in Klarna's system, accomplished by the merchant presenting recommended products on the confirmation page. If the customer buys an additional product, the confirmed order of the customer is updated within the shown iFrame and the product is added. For a technical description of how to integrate Cross-sell, see: https://developers.klarna.com/en/se+php/kco-v2/checkout/use-cases#cross-sell

**Comment by NiklasHogefjord** [comment] 2018-12-07 11:14
@kristibarbosky is it confirmed that the merchant wanting this feature is using v3?

**Comment by kristibarbosky** [comment] 2018-12-07 19:41
Confirming that this ticket does cover KCOv3 (not KCOv2).  Also note: this cross-sell functionality should only be offered for Pay Later orders so the code will need to check the payment method to determine when this should be offered.

**Comment by NiklasHogefjord** [comment] 2018-12-10 14:57
OK, thanks Kristi. Will look into it.

**Comment by kristibarbosky** [comment] 2018-12-14 17:00
Klarna will enable the functionality for additional payment methods (not just pay_later), thus the integrating code shouldn't be tied to a Klarna payment method, but should be configurable for a merchant.

**Comment by NiklasHogefjord** [comment] 2020-11-03 09:27
Closing this since it won't be a part of the Klarna checkout plugin.

**Closed by NiklasHogefjord** 2020-11-03 09:27 UTC
Labels: enhancement
