### ISSUE TITLE
Empty checkbox appearing from time to time.

### ISSUE THREAD

**Issue by Preen** [krokedil/klarna-checkout-for-woocommerce#379] opened 2021-02-25 10:22 UTC
### Description of the issue
As shown in the video we get an empty checkbox appearing from time to time.

### Expected behavior
Not an empty checkbox

### Actual behavior
Checkbox appears from time to time.

### Steps to reproduce the behavior
Just watch the video.

### Klarna plugin version
2.4.2

### WordPress version
5.6.2

### WooCommerce version
4.9.2
### Screenshots

https://user-images.githubusercontent.com/364479/109139312-aa6e0b80-775b-11eb-87dd-339cb220fd70.mp4

### Before submitting
Make sure to try the following steps before you submit the issue
* Update the plugin to the latest version and test again.
* Test with the [Storefront](https://wordpress.org/themes/storefront/) theme.
* Deactivate any other plugin except WooCommerce and Klarna Checkout for WooCommerce and test again.

**Comment by MichaelBengtsson** [comment] 2021-03-09 15:05
@Preen Hi!

Sadly i am not able to reproduce this issue at all. Would it be possible for you to get the log for an order when this happens and show me what the options element looks like in the request? There might be something in there that is causing this.

**Comment by MichaelBengtsson** [comment] 2021-03-22 22:04
I have not been able to recreate this issue and we have not gotten this reported by anyone else. So until we get some logs to look at we cant really do anything with this. I will close this issue for now, but if you come back with logs we will take a look at this again and you can reopen the issue.

**Closed by MichaelBengtsson** 2021-03-22 22:04 UTC
