### ISSUE TITLE
Duplicate order was created in Woo & merchant references are missing in the Klarna order

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#18] opened 2018-01-10 22:37 UTC
This issue happened in production:

2 orders were created in Woo.

Klarna shows an error when the single Klarna order got a merchant_update_order_v3 after the order was checkout_complete (this is the only error that showed up in the Woo Klarna logs):

"operation" : "merchant_update_order_v3",
  "Klarna-Correlation-Id" : "5367af52-803d-44a4-9361-bfb7e9cd0866",
      "Content-Type" : "application/json"
    },
    "body" : {
      "error_code" : "READ_ONLY_ORDER",
      "error_messages" : [ "Resource is read-only" ],
      "correlation_id" : "5367af52-803d-44a4-9361-bfb7e9cd0866"
    }

In Klarna, the merchant references were not updated as they should have been.

![image](https://user-images.githubusercontent.com/15654455/34803500-a8586bcc-f641-11e7-8831-7b3794a51ab3.png)

![image](https://user-images.githubusercontent.com/15654455/34803540-d3e00cf0-f641-11e7-9bea-03d07c8ecd3b.png)

failed  "operation" : "merchant_update_order_v3",
  "request" : {
    "timestamp" : "2018-01-10T21:48:19Z"

successful "operation" : "payment_confirmation_request_v1",
  "request" : {
    "timestamp" : "2018-01-10T21:48:07Z",

successful   "operation" : "merchant_update_order_v3",
  "request" : {
    "timestamp" : "2018-01-10T21:47:41Z"

**Comment by kristibarbosky** [comment] 2018-01-11 03:14
A 3rd order (another duplicate) was created in Woo (for this same Klarna order id) a few hours after the previous orders.  It was in processing status.

**Comment by NiklasHogefjord** [comment] 2018-01-11 13:27
Sorry about this. The problem is probably because it is an order created via our backup order creation feature where we had missed to acknowledge the order and update your system with the store order number.

Should be fixed in 9cf361d90f012365a1ca310b43b6aa7858dc5833 and 13f9421e60ba66a3b665bd8b37510c661e499769

**Closed by NiklasHogefjord** 2018-01-11 13:27 UTC
