### ISSUE TITLE
WooCommerce total and Klarna total do not match

### ISSUE THREAD

**Issue by niklaswallerstedt** [krokedil/klarna-checkout-for-woocommerce#42] opened 2018-04-22 21:04 UTC
Hi, We've been using v3 live for a week or so and it has been working well, but we received an order this evening where totals between Woocommerce and Klarna are different.

> Order needs manual review, WooCommerce total and Klarna total do not match. Klarna order total: 77800. Order status changed from Processing to On hold.

From WC:

SKU: 240 | 25,20 kr | × 1 | 25,20 kr | 6,30 kr |  
SKU: 420 | 34,40 kr | × 1 | 34,40 kr | 8,60 kr | 

Total: 74,50

What could be the cause of this? The faulty order has also lost information about variations in WC, but not in Klarna.

I'm also seeing a lot of errors in the log, even though orders are completing fine with correct amounts except for the one above. Is this normal behavior? 

`018-04-22T20:22:20+00:00 ERROR Retrieve ongoing Klarna order`
`2018-04-22T20:48:48+00:00 ERROR Create Klarna order`
`2018-04-22T22:11:58+00:00 ERROR Update ongoing Klarna order (https://api.klarna.com/checkout/v3/orders/...) {"headers":{"Authorization":"Basic ...","Content-Type":"application\/json"},"user-agent":"WordPress\/4.9.5; ... - KCO:1.3.0"`

I'm trying to recreate this on our sandbox-site, might be some issue with another plugin.

**Comment by kristibarbosky** [comment] 2018-04-23 02:42
Klarna logs show:

  	 exception:	 com.klarna.merchantapi.resources.exception.InvalidAuthorizationAmountException: Cannot increase order amount.
	at com.klarna.merchantapi.resources.OrderFacade.updateAuthorization(OrderFacade.java:101)
	at com.klarna.merchantapi.resources.OrderResource.updateAuthorization(OrderResource.java:219)

  	 timestamp:	 2018-04-22T21:28:42.471Z	
  	 uid:	 79ba8443-aa97-48c6-bfc4-1fc050457e8f	

@niklaswallerstedt - Was the order altered in Woo after the order was placed by the customer?

**Comment by niklaswallerstedt** [comment] 2018-04-23 05:51
@krisibarbosky just to clarify, the error logs above were from multiple orders. Regarding the faulty order, it was altered afterwards in WC but this set the order total in Klarna to 74,50 SEK instead of 778 SEK. The order value could then not be raised to the original amount. I’ve also raised this to merchant support.

**Comment by niklaswallerstedt** [comment] 2018-04-23 14:27
Spoke to merchant support today, they cannot correct the order afterwards. But still, wondering why the WC order was 74,50 SEK to begin with?

**Comment by NiklasHogefjord** [comment] 2018-04-23 14:58
Hi @niklaswallerstedt,
I'm guessing you also have an order note saying _Order created via Klarna Checkout API Callback._ in that order?

The root cause to this problem is that the order could not be created in front end when the customer actually finalized the purchase (but instead 2 minutes later on a server-to-server-call between Klarna and the webstore).

We will improve how this is handled (with a fallback order creation in frontend when WC checkout form submission fail).  We will also take a closer look at the current way we handle product variations on the server-to-server-call.

I'll get back with an update within a day or two.

**Comment by niklaswallerstedt** [comment] 2018-04-23 15:09
@NiklasHogefjord, Yes that is correct, that's the only order so far via API callback. Thanks for the input on the issue. Please let me know if I can assist somehow.

**Comment by kristibarbosky** [comment] 2018-04-24 01:58
@niklaswallerstedt - further review of the logs show:

1. The customer placed the order (for order_total 77800 SEK) ["timestamp" : "2018-04-22T18:51:33Z"]

2. A transaction from the Woo admin initiated an order management call that updated the order as follows::	 {"order_amount":7450,"order_lines":[{"reference":"240","name":"Pocket harem leggings - Black","type":"physical","quantity":1,"unit_price":3150,"total_amount":3150,"total_discount_amount":0,"tax_rate":2500,"total_tax_amount":630},{"reference":"420","name":"Panda Onesie - Black","type":"physical","quantity":1,"unit_price":4300,"total_amount":4300,"total_discount_amount":0,"tax_rate":2500,"total_tax_amount":860},{"reference":"free_shipping:2","name":"Free Shipping","type":"shipping_fee","quantity":1,"unit_price":0,"total_amount":0,"total_discount_amount":0,"tax_rate":0,"total_tax_amount":0}]}	[timestamp:	 2018-04-22T21:15:27.416Z]

3. Klarna does not allow the order_total to be increased by a merchant; once the order_total was reduced, it cannot be subsequently increased.

The order being reduced shows to be a result of a Woo admin order update.  Please let us know if you have further questions or issues regarding how Woo and Klarna order totals ended up not matching.

**Comment by niklaswallerstedt** [comment] 2018-04-26 12:13
This happened for another order, I can see that you are working on this in develop though.

Order sent to Klarna was 349 SEK, in WC it’s 33,50 SEK. On the last order I tried to correct the the total but by accident sent an update. How do I safely update the order without changing the total in Klarna?

**Comment by MichaelBengtsson** [comment] 2018-04-26 14:13
Hi @niklaswallerstedt !

We are currently working on a new fallback that will create the order from the cart instead of on the push back from Klarna. This should hopefully fix some issues that you might be having currently. This is currently in one of our develop branches, and will be released soon.

Untill this is fixed however, you can manage your orders in Klarna Playground, like activating the order and so on. I would suggest using that as a work arround for now.

**Comment by NiklasHogefjord** [comment] 2018-05-01 08:55
Hi @niklaswallerstedt,
Version 1.4.0 is now released (https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.4.0). This version should solve your problem.

I'm closing this ticket now. Please feel free to reopen it again if the problem continues even after the update.

**Closed by NiklasHogefjord** 2018-05-01 08:55 UTC

**Comment by erssn** [comment] 2018-05-09 09:01
Hi @NiklasHogefjord. We now have the same problem, even with 1.4.0 installed. Though, we are currently using klarna in test mode. Any ideas? What do you need for type of information?

![untitled2](https://user-images.githubusercontent.com/39119111/39805845-47733604-5378-11e8-9531-64db4e966dbf.jpg)

Link: https://usaonline.se

**Comment by virik** [comment] 2018-10-22 09:20
Hi, @erssn.

Did you figure out this one? We are experiencing the same issue in our store.

Thanks.

**Comment by NiklasHogefjord** [comment] 2018-10-23 07:46
When this happens it is usually a compatibility issue with another plugin or a setting in WooCommerce that conflicts with the Klarna Checkout plugin.

Here is a link to a flow chart describing the intended flow: https://docs.woocommerce.com/document/klarna-checkout-integration-flow-chart/.

If you keep experiencing problems after deactivating other plugins please send a support ticket to support@krokedil.com and we will help you out.

**Comment by niklaswallerstedt** [comment] 2018-11-08 20:49
@NiklasHogefjord I haven't seen this problem since I created this issue, but something similar happened again today. The same customer had two orders in WC:

- Order A is pending payment with 12 items for 3 021 SEK
- Order B is On hold with 10 items for 392 SEK

However in Klarna, there is only one entry for 3 021 SEK with B's order number. Order B is also missing variation data, which explains why there are two items less.

We have 1 order created as a fallback on the status page.

I will activate the order in Klarna first before trying to change them. I haven't had the chance to update to the latest version of your plugin yet so might be something you have addressed.

**Order A**

> There are no notes yet.

**Order B**

> Order needs manual review, WooCommerce total and Klarna total do not match. Klarna order total: 302100. Order status changed from Processing to On hold.

**Klarna**

15:16

Uppdaterade butiksreferenser <-- Order number is overwritten
Referens 1: "Order B"
Referens 2: "Order B"

Via API

15:16
Order bekräftad

Via API

15:14 <-- Order A was created
Order skapad: 3 021,00 kr
