### ISSUE TITLE
Address and name not changed on the order

### ISSUE THREAD

**Issue by rafal-sokolowski** [krokedil/klarna-checkout-for-woocommerce#206] opened 2019-04-30 10:55 UTC
Klarna Checkout for WooCommerce 1.9.2
WooCommerce >= 3.6.0

When a customer is logged in, and they made a purchase in the past, placing a new order with a different address and/or name doesn't work as it should. The address and the name are not changed but the ones from the previous order are used instead.

It works fine with WooCommerce <= 3.5.8.

**Comment by yratof** [comment] 2019-05-02 11:11
Same issue with a multisite happening here... is this a caching issue?

**Comment by NiklasHogefjord** [comment] 2019-05-06 07:40
Hi @rafal-sokolowski, thanks for reporting this.

It seems to be a bug related to how/when WC 3.6 sets the customer object during rendering of the checkout (https://github.com/woocommerce/woocommerce/commit/4672a47d67855969efd4908804c76e2044a57cbe#diff-1144db956b12f18d5935fdc3989109b3R1160).

We have an update in this commit - 397b64bb7296db3535d33c27bf9a899e0da3010d - that should solve the problem. 

The fix is included in the new version 1.9.5. I'm closing this issue now but feel free to re-open it again if the problem isn't solved by the new version.

**Closed by NiklasHogefjord** 2019-05-06 07:40 UTC
