### ISSUE TITLE
Should we investigate if there is a way to auto exclude checkout.bootstrap.js from cache

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#118] opened 2018-10-25 14:42 UTC
We've had a couple of support tickets where the file (https://a.klarnacdn.net/kcoc/181024-f5f3b70/checkout.bootstrap.js) have been served from disk and not from Klarnas CDN.

**Comment by NiklasHogefjord** [comment] 2018-10-25 14:43
This causes the Ooops error message. Lately it was a a conflict with the WP Rocket caching plugin.

**Comment by MichaelBengtsson** [comment] 2018-11-15 10:43
This was not the cause of the Ooops error message. Closing this for now.

**Closed by MichaelBengtsson** 2018-11-15 10:43 UTC
Labels: enhancement
