### ISSUE TITLE
Support subscriptions/recurring orders for KCOv3

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#48] opened 2018-05-18 02:06 UTC
v3: https://developers.klarna.com/en/gb/kco-v3/checkout/extra-merchant-data

https://developers.klarna.com/api/#checkout-api__create-a-new-orderattachment__body__subscription

Attach the subscription info into the  'attachment' field when initialize the checkout, there will be one order created and payment will be taken automatically

**Comment by kristibarbosky** [comment] 2018-05-18 14:30
KCOv3 subscriptions are currently available for Sweden, Norway, & Finland (similar to KCOv2).  Order should be created in Woo by our plugin, using the token returned for the 1st order.

**Comment by kristibarbosky** [comment] 2018-05-22 21:11
@MichaelBengtsson  - I've updated to allow recurring for SE, GB, and DE for K500956

![image](https://user-images.githubusercontent.com/15654455/40390186-628a244c-5de2-11e8-9eed-94930ea93e14.png)

add following to the create_order KCOv3 call:     "recurring": true,
    "recurring_description": "Test Recurring",

in the response of KCO you should get a recurring_token parameter

**Comment by kristibarbosky** [comment] 2018-09-20 13:53
@MichaelBengtsson - please add the Klarna order id to the Woo order

**Comment by NiklasHogefjord** [comment] 2018-09-25 15:29
@MichaelBengtsson I see that you have added it as an order note in 1a8e4daf54b3a0d187b712aa188ba5fca278ee10, however you also need to set it in __transaction_id_ so we can use it for order management. Just as with a regular order.

**Comment by NiklasHogefjord** [comment] 2018-09-26 06:19
- [ ] Add Klarna order id to [payment_complete()](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/develop-subscription/includes/class-klarna-checkout-for-woocommerce-subscription.php#L173) function.

- [ ] Remove [create_extra_merchant_data](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/develop-subscription/includes/class-klarna-checkout-for-woocommerce-subscription.php#L63) function if it's not in use.

- [ ] change _kco_recurring_token_ to __kco_recurring_token_ and display it in the order details meta box in the Subscription (and in parent and renewal orders as well?). Make this field editable.

- [ ] Test and implement support for switching from another payment method to KCO.

- [ ] Test and implement support for updating payment method/card when having KCO set as payment method for an ongoing subscription (e.g create a new recurring token).

**Comment by MichaelBengtsson** [comment] 2018-09-26 06:35
@NiklasHogefjord $renewal_order->set_transaction_id( $klarna_order_id ); on row 170 of the subscription class in that commit. I set the transaction id there.

**Comment by NiklasHogefjord** [comment] 2018-09-26 06:47
@MichaelBengtsson Ah, sorry. Didn't see that.

**Comment by cturnbull** [comment] 2018-10-01 09:39
Hello, I have a request with regards to recurring payments that I would like to submit here for your consideration.

[Subscription switching functionality](https://docs.woocommerce.com/document/subscriptions/switching-guide/) (upgrades, downgrades, "crossgrades") compatibility: this is a useful feature of WooCommerce Subscriptions that applies mostly to variable subscription and grouped products, but also with non-subscription products given subscription schemes via the mini WCS extension [Subscribe All The Things](https://github.com/Prospress/woocommerce-subscribe-all-the-things). 

I could not get this working successfully with the older v2 KCO plugin, so I wondered if this was an perhaps an oversight, and whether this will be possible with the more WC-standardised checkout flow that this new plugin features (which looks really good, by the way).

**Comment by mrtnsn** [comment] 2018-11-07 23:56
Hi, what's the status on this? I'm using this plugin for a new site we're developing and i'm running into `Bad value: recurring`.

From what I can tell it's due to `create_extra_merchant_data()` not being fully implemented, is that correct?

**Comment by kristibarbosky** [comment] 2018-11-08 02:11
@mrtnsn - we have tested recurring with KCOv3 and it was working successfully.  Regarding your error, can you provide your MID and/or your correlation_id so we can review the error in the Klarna logs?  Extra merchant data is not required for KCOv3.

Please note: by default, Klarna MIDs are not configured to support recurring orders.  Playground MIDs require updates to support recurring testing; production MIDs require contracts for recurring.  Has your MID been configured for recurring?

**Comment by mrtnsn** [comment] 2018-11-08 02:13
I will have a chat with our customer about that. I'm guessing that's the cause of the issue. Thank you for a very swift response.

**Comment by cturnbull** [comment] 2018-11-09 13:16
@mrtnsn @kristibarbosky I have been burned by this, thinking recurring payments was now a solution offered by Klarna, but after a great deal of waiting for the integration department to get back to me, it is apparently not ready (at least in Norway, see below for the answer I received from integration department). I am still waiting to see if I can even get a playground agreement to have recurring payment support added.

Fascinatingly, there is an article [here](https://knowledge.klarna.com/article/klarna-offer-support-recurring-payments/) saying recurring payments is now "ready":

> Since the launch of Klarna Checkout, one of the most eagerly awaited features has been support for recurring payments. It’s happening now, in KCO V3.
> [...] So, we are very happy to be able to say that we now support recurring payments in KCO, v3.

... with no date for said support to be made live. One is led to believe that it is in fact ready. Article then links to a developer article [here](https://developers.klarna.com/en/gb/kco-v3/checkout/recurring/):

> This feature is only available in Nordics and DACH at the present time, if you have a need for more markets contact your Klarna rep

Via email correspondence with integration department, per 1. November:

> From Klarna's end we have not actively started with agreements yet for recurring payments with v3.

The agent is aware, afaik, that this is for a Norwegian merchant agreement.

There is so much contradicting information from Klarna on the subject of recurring payments that I don't know who to believe anymore. According to merchant support, recurring payments for v3 is only available for UK at the moment (contradicting the dev article on the subject).

Maybe you could clear this up for us once and for all @kristibarbosky?

**Comment by NiklasHogefjord** [comment] 2018-11-09 14:12
@mrtnsn @cturnbull 

Recurring payments via WooCommerce Subscriptions have been implemented in this plugin since of version 1.7.0. 

At the moment the following countries are supported:

- Sweden
- Norway
- Finland
- Germany
- Austria

Documentation can be found here: https://docs.woocommerce.com/document/klarna-checkout-recurring-payments/

If Klarnas sales team give you the answer that recurring payments isn't ready for KCO v3 yet I think it's better that you get in direct contact with us at Krokedil (at support@krokedil.com) and we will try to help you in the right direction when it comes to talking to the right Klarna representative.

I will close this issue now since I don't think this is a technical issue.

**Closed by NiklasHogefjord** 2018-11-09 14:12 UTC
Labels: enhancement, has fix

**Comment by kristibarbosky** [comment] 2018-11-09 14:29
@cturnbull  - thank you for documenting this and I apologize for your frustration.  I've escalated this mismatch of information internally.
