### ISSUE TITLE
Change KCO iframe background

### ISSUE THREAD

**Issue by engineerized** [krokedil/klarna-checkout-for-woocommerce#272] opened 2020-01-14 16:05 UTC
Hi, is there any way to set KCO iframe background? The background is now set per default to white at` <body style="background: white; margin: 0">`

I tried to add script to change the color but didn't work.

It would be very helpful if we could set the background color at Color Settings in Woo admin.

Thanks in advance.

**Comment by kristibarbosky** [comment] 2020-01-17 15:54
Hi @engineerized  -
I'm closing this ticket as this is not a bug in the Woo KCO plugin.  At this time, the Klarna Checkout product does not offer the option to customize the KCO iframe background, and thus we can not support this via Woo KCO.  Available KCO color customizations documented at: https://developers.klarna.com/api/#checkout-api__create-a-new-order__options

I believe is by design from the Klarna Checkout team to not make the KCO iframe background customizable (i.e. to be supportive and compliant to ensure the KCO iframe is always readable for all customers).

**Closed by kristibarbosky** 2020-01-17 15:54 UTC
